<template>
  <div class="home">
    <h1 class="huge-head animate__animated animate__flipInX animate__slow">
      myMentor
    </h1>

    <div class="container desktop">
      <div class="row">
        <div class="col-lg-6 col-md-6">
          <router-link to="/login"><p class="subby">LOGIN</p></router-link>
        </div>
        <div class="col-lg-6 col-md-6">
          <router-link to="/register"
            ><p class="subby">REGISTER</p></router-link
          >
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {};
</script>
<style scoped>
.home {
  background: linear-gradient(0deg, rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7)),
    url("../assets/ocean.jpg");
  background-position: center;
  padding-top: 10%;
  height: 100vh;
  overflow: hidden;
}
.huge-head {
  font-size: 150px;
  color: white;
}
a {
  text-decoration: none;
}
p {
  padding-top: 20px;
  padding-bottom: 20px;
  background: rgb(17, 20, 64);
  font-size: 20px;
  border: none;
  border-radius: 25px;
  color: white;
}

.container {
  padding-top: 10%;
}
.mobile {
  display: none;
}
.mobi-link {
  border-radius: 25px;
  border: solid 5px rgb(52, 152, 235);
  text-decoration: none;
  width: 100%;
  padding-top: 10px;
  padding-bottom: 10px;
  padding-left: 20px;
  padding-right: 20px;
  margin: 30px;
}
/* media queries */
@media only screen and (max-width: 600px) {
  .home {
    padding-top: 30%;
  }
  .huge-head {
    font-size: 70px;
  }
  .row {
    padding-top: 15%;
  }
}
/* animations */
.pulsate-bck {
  -webkit-animation: pulsate-bck 0.5s ease-in-out infinite both;
  animation: pulsate-bck 0.5s ease-in-out infinite both;
}
/* ----------------------------------------------
 * Generated by Animista on 2022-3-22 18:48:11
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation pulsate-bck
 * ----------------------------------------
 */
@-webkit-keyframes pulsate-bck {
  0% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
  50% {
    -webkit-transform: scale(0.9);
    transform: scale(0.9);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
@keyframes pulsate-bck {
  0% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
  50% {
    -webkit-transform: scale(0.9);
    transform: scale(0.9);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
</style>
