<template>
  
  <router-view/>
  <Footer/>
</template>
<script>
import Nav from "./components/Navbar.vue"
import Footer from "./components/Footer.vue"
export default {
  components: {
    Footer,Nav
  }
  
}
</script>
<style >
*{
  font-family: 'Oswald', sans-serif;
}
body{
  overflow: initial !important;;
}
#app {
  height: 100vh !important;
width: 100% !important;
overflow: none !important;
  margin: 0 !important;
 
font-family: 'Bebas Neue', cursive;
font-family: 'PT Serif', serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  background:linear-gradient(0deg, rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7)), rgb(17, 20, 64);

}
h1{
  color: white
}
.heading{
   color: rgb(52, 152, 235);
   text-decoration: underline;
}
.subby:hover{
  animation-name: pulsate-bck;
  animation-iteration-count: infinite;
  animation-duration: 0.5s;
}

/* width */
::-webkit-scrollbar {
  width: 15px;
}

/* Track */
::-webkit-scrollbar-track {
  background: transparent; 
}
 
/* Handle */
::-webkit-scrollbar-thumb {
  background: rgb(52, 152, 235); 
  border-radius: 25px;
}

/* Handle on hover */
::-webkit-scrollbar-thumb:hover {
  background: rgb(29, 7, 228); 
}
@import url('https://fonts.googleapis.com/css2?family=Bebas+Neue&family=PT+Serif&display=swap');
/* animation */
.pulsate-bck {
	-webkit-animation: pulsate-bck 0.5s ease-in-out infinite both;
	        animation: pulsate-bck 0.5s ease-in-out infinite both;
}
/* ----------------------------------------------
 * Generated by Animista on 2022-3-22 18:48:11
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation pulsate-bck
 * ----------------------------------------
 */
@-webkit-keyframes pulsate-bck {
  0% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
  50% {
    -webkit-transform: scale(0.9);
            transform: scale(0.9);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}
@keyframes pulsate-bck {
  0% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
  50% {
    -webkit-transform: scale(0.9);
            transform: scale(0.9);
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
  }
}
</style>
//TDL2627